name: Test for terraform-docs bug report.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
      
    steps:
    
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: |
        terraform init
        terraform validate
    
    - name: Checkout head for terraform-docs commit
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
